### ISSUE TITLE
InsertBatch TSV

### ISSUE THREAD

**Issue by KnBrBz** [leprosus/golang-clickhouse#3]
No luck inserting tab separated batch
```go
values = "SomeString\t1593706543\t245.6\t246.5\t245.7\t100\t1593706543456\t16\t10000\n" +
	"SomeString2\t1593706544\t245.6\t246.5\t245.7\t101\t1593706544456\t16\t10001\b"	
err = conn.InsertBatch("db", "table", columns, ch.TSV, strings.NewReader(values))
```
For my case reading from file is not useful.

Got error
Catch error Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\n' before: '\b\n': (at row 2)

Got it working in such a way
```go
values := "('SomeString',1593706543,245.6,246.5,245.7,100,1593706543456,16,10000),('SomeString2',1593706544,245.6,246.5,245.7,101,1593706544456,16,10001);\b"
err = conn.InsertBatch("db", "table", columns, "Values", strings.NewReader(values))
```

**Comment by leprosus** [comment]
you have an answer in error trace 
```
Catch error Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected '\n' before: '\b\n': (at row 2)
```

It means you input contains unexpected for Clickhouse symbol `\b`
Please just filter you input removing unexpected symbols

I used the driver for a similar aim and it works well with TSV
